site_name: JustinWritesCode Common Documentation
site_description: JustinWritesCode Documentation
site_url: https://justinwritescode.com
site_author: "Justin Chase"
repo_url: https://github.com/justinwritescode/nuget-icons
repo_name: justinwritescode/nuget-icons
edit_uri: "tree/main/docs"
docs_dir: docs