name: Security Vulnerability Report
description: File a security vulnerability report
title: "[Security]: "
labels: ["security", "triage"]
assignees:
  - justinwritescode
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this security vulnerability report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: e.g., email@example.com
    validations:
      required: true
  - type: textarea
    id: whats-wrong
    attributes:
      label: Describe the vulnerability
      description: A clear and concise description of what the vulnerability is.
      placeholder: What's wrong?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: |
        ![screenshot]()
    validations:
      required: false
  - type: dropdown
    id: tech-affected
    attributes:
      label: What technologies does this affect?
      multiple: true
      options:
        - .NET Core
        - ASP.NET Core
        - Azure
        - Azure DevOps
        - Azure Functions
        - Azure Pipelines
        - Azure SDK
        - Azure Storage
        - Azure Web Apps
        - C#
        - Cosmos DB
        - Docker
        - GitHub
        - GitHub Actions
        - GitHub CLI
        - GitHub Desktop
        - MSBuild
        - NuGet
        - PowerShell
        - Other
  - type: dropdown
    id: devices-affected
    attributes:
      label: What devices does this affect?
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
        - Chrome OS
        - Other
  - type: dropdown
    id: browsers-affected
    attributes:
      label: What browsers does this affect?
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other